version: '3'

# TODO: verificar se está criando os volumes

services:
  chatservice:
    build: .
    container_name: chatservice__app
    volumes:
      - .:/go/src
    ports:
      - "8080:8080" # porta da aplicação
      - "50051:50051" # porta do gRPC

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_test
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql